distribute/urls.py
from django.urls import path
from distribute import views

app_name = 'distribute'

urlpatterns =[
    path('<int:llm_id>/', views.distribute, name='distribute'),
    path('<int:llm_id>/unpublic/', views.unpublish_llm, name= 'unpublic'),



    path('distribute_app/<int:llm_id>/', views.distribute_app, name= 'distribute_app'),

    path('<int:llm_id>/unpublish_llm_app/', views.unpublish_llm_app, name= 'unpublish_llm_app'),


]

galatea/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views
from django.views.i18n import set_language
from django.utils.translation import get_language
from django.shortcuts import redirect
from celebrity import views as celebrity_views
from customer_ai import views as customer_ai_views
from makeImage import views as make_image_view
from register import views as login_view
from home import views as main_view
from makeVoice import views as make_voice_view
from helpdesk import views as helpdesk_view
from payment import views as payment_view
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap
from django.views.generic import TemplateView




def root_redirect(request):
    lang = get_language()
    return redirect(f'/{lang}/')

sitemaps = {
    "static": StaticViewSitemap,
}
urlpatterns = [
    path('', root_redirect),  # 루트 접속 시 언어별 URL로 리다이렉트
    path('admin/', admin.site.urls),
    path('i18n/setlang/', set_language, name='set_language'),
    path('accounts/', include('allauth.urls')), 

    path('celebrity/celebrity_audio/', celebrity_views.celebrity_audio, name='celebrity_audio'),
    path('celebrity/<int:celebrity_id>/response/', celebrity_views.celebrity_response, name='celebrity_response'),
    path('upload_audio/', customer_ai_views.upload_audio, name='upload_audio'),
    path('generate_response/', customer_ai_views.generate_response, name='generate_response'),
    path('vision_process/', customer_ai_views.vision_process, name='vision_process'),
    path('novel_process/', customer_ai_views.novel_process, name = "novel_process"),

    path("generate_image/", make_image_view.generate_image, name="generate_image"),
    path('proxy_image/', make_image_view.proxy_image, name='proxy_image'),  # 이미지 프록시용
    path('<int:llm_id>/introduce', main_view.distribute_llm, name='distribute_llm'),
    path("auto_generate_prompt", make_voice_view.auto_generate_prompt, name="auto_generate_prompt") ,           
    path("auto_prompt/", customer_ai_views.auto_prompt, name="auto_prompt"),
    path("payment/complete/", payment_view.payment_complete, name="payment_complete"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("robots.txt", TemplateView.as_view(
        template_name="robots.txt",
        content_type="text/plain"
    )),



]



urlpatterns += i18n_patterns(
    
    path('', include('home.urls', namespace='home')),  # home.urls 안에 main/ 포함
    path('celebrity/', include(('celebrity.urls', 'celebrity'), namespace='celebrity')),
    path('customer_ai/', include(('customer_ai.urls', 'customer_ai'), namespace='customer_ai')),
    path('image/', include(('makeImage.urls', 'makeImage'), namespace='makeImage')),
    # path('make_voice/', include(('makeVoice.urls', 'makeVoice'), namespace='makeVoice')),
    path('register/', include(('register.urls', 'register'), namespace='register')),
    path('logout/', home_views.user_logout, name='logout'),
    path('mypage/', include(("mypage.urls","mypage"), namespace="mypage")),
    # path('cloning/', include(('cloning.urls', 'cloning'), namespace='cloning')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path("distribute/", include(("distribute.urls", 'distribute'), namespace="distribute")),
    path('intro/<int:llm_id>/', main_view.llm_detail_partial, name='llm_detail_partial'),
    path('helpdesk/', include(("helpdesk.urls", 'helpdesk'), namespace='helpdesk')),
    path('invest/', include(("invest.urls", 'invest'), namespace='invest')),



    path('api/', include(('customer_ai.urls', 'customer_ai'), namespace='customer_ai_api')),


)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
from home import views as home_views

handler400 = 'home.views.bad_request'
handler403 = 'home.views.permission_denied'
handler404 = 'home.views.page_not_found'
handler500 = 'home.views.server_error'

home/urls.py
from django.urls import path
from home import views
from django.views.i18n import set_language

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),  
    path('main/', views.main, name='main'),
    path('logout/', views.user_logout, name='logout'),
    path('i18n/setlang/', set_language, name='set_language'),
    path('follow/', views.follow_toggle, name = "toggle_follow"),
    path('like/', views.like_toggle, name = 'like_toggle'),
    path('llm/<int:llm_id>/', views.llm_intro, name='llm_intro'),
    path('genres/', views.gerne_all, name= 'genre_all'),
    path('search/', views.search_llm, name = 'search_llm'),
    path('genres/<int:genres_id>', views.genre_detail, name='genres_detail'),
    path('llm_sections/', views.llm_section, name='llm_section'),
    path('comment_create/<int:llm_id>', views.comment_create, name="comment_create"),

    path("voice_all/", views.voice_all, name="voice_all"),
    path("save_voice/", views.save_voice, name="save_voice"),
    path("user_intro/<int:user_id>/", views.user_intro, name="user_intro"),
    path("soon/", views.soon, name="soon"),
    path('invite/', views.invite, name='invite'),


    # path('like/<int:llm_id>/', views.like_toggle, name = "like_toggle"),


    # 앱 전용
    path("app/", views.home_app_view, name="home_app"),
    path("main_app/", views.main_app, name="main_app"),
    path("llm_intro_app/<int:llm_id>/", views.llm_intro_app, name="llm_intro_app"),
    path("llm_section_app/", views.llm_section_app, name="llm_section_app"),
    path("gerne_all_app/", views.gerne_all_app, name="gerne_all_app"),
    path("search_llm_app/", views.search_llm_app, name="search_llm_app"),
    path("genres_detail_app/<int:genres_id>/", views.genres_detail_app, name="genres_detail_app"),
    path("invite_app/", views.invite_app, name="invite_app"),
    path('logout_app/', views.logout_app, name='logout_app'),
    path('voice_all_app/', views.voice_all_app, name='voice_all_app'),
    path('search_result_app/', views.search_result_app, name='search_result_app'),
    path('user_intro_app/<int:user_id>/', views.user_intro_app, name='user_intro_app'),

]


mypage/urls.py
from django.urls import path
from mypage import views

app_name = 'mypage'

urlpatterns = [
    path('', views.mypage_view, name='mypage'),
    path('update/', views.mypage_update, name='mypage_update'),
    path('<int:user_id>/', views.mypage_update, name='mypage_update'),
    path('my_voice/', views.my_voice, name='my_voice'),
    path('my_ai_models/<int:llm_id>/', views.my_ai_models, name='my_ai_models'),
    path('my_ai_conversation/<int:llm_id>/', views.my_ai_conversation, name="my_ai_conversation"),
    path('token/', views.personal_token, name = 'token'),
    path('upload-profile-image/', views.upload_profile_image, name='upload_profile_image'),
    path('my_ai_models/update/<int:llm_id>', views.my_ai_models_update, name='my_ai_models_update'),
    path('my_ai_models/delete/<int:llm_id>', views.my_ai_models_delete, name='my_ai_models_delete'),
    # path('<int:voice_id>/toggle_public/', views.toggle_voice_public, name='toggle_voice_public'),
    path("my_custom/", views.my_custom, name= "my_custom"),
    path("my_request/", views.my_request, name= "my_request"),
    path("my_coupon/", views.my_coupon, name= "my_coupon"),
    path("myvoice/delete/<int:voice_id>/", views.my_voice_delete, name="my_voice_delete"),
    path('personal_profile/', views.personal_profile, name="personal_profile"),
    path('llm_like/', views.llm_like, name="llm_like"),
    path('follow_list/', views.follow_list, name="follow_list"),
    path("unpublish_llm/<int:llm_id>/", views.unpublish_llm, name="unpublish_llm"),
    path('prompt_share/<int:prompt_id>/delete/', views.prompt_share_delete, name='prompt_share_delete'),
    path('prompt_share/<int:prompt_id>/update/', views.prompt_share_update, name='prompt_share_update'),
    path('intro/<int:llm_id>/', views.llm_intro, name='llm_intro'),
    path('token_less/', views.token_less, name='token_less'),
    

    path("mypage_app/", views.mypage_app, name="mypage_app"),
    path('sidebar_app/', views.sidebar_app, name='sidebar_app'),
    path('mypage_update_app/', views.mypage_update_app, name='mypage_update_app'),
    path('my_ai_models_app/<int:llm_id>/', views.my_ai_models_app, name='my_ai_models_app'),
    path('my_ai_conversation_app/<int:llm_id>', views.my_ai_conversation_app, name='my_ai_conversation_app'),
    path('my_voice_app/', views.my_voice_app, name='my_voice_app'),
    path('my_voice_delete_app/', views.my_voice_delete_app, name='my_voice_delete_app'),
    path('my_ai_models_update_app/<int:llm_id>/', views.my_ai_models_update_app, name='my_ai_models_update_app'),
    path('follow_list_app/', views.follow_list_app, name='follow_list_app'),
    path('my_coupon_app/', views.my_coupon_app, name='my_coupon_app'),
    path('token_less_app/', views.token_less_app, name='token_less_app'),
    path('personal_profile_app/', views.personal_profile_app, name='personal_profile_app'),
    path('my_request_app/', views.my_request_app, name='my_request_app'),
    path('llm_like_app/', views.llm_like_app, name='llm_like_app'),
    path('token_app/', views.token_app, name='token_app'),
    path('unpublish_llm_app/<int:llm_id>/', views.unpublish_llm_app, name='unpublish_llm_app'),
    path('my_ai_models/delete_app/<int:llm_id>', views.my_ai_models_delete_app, name='my_ai_models_delete_app'),


]

distribute/models.py
from django.db import models
from mypage.models import Genre
from django.conf import settings

# 댓글 테이블
# Create your models here.
class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    llm = models.ForeignKey('customer_ai.LLM', on_delete=models.CASCADE)
    content = models.TextField(verbose_name='댓글')
    created_at = models.DateTimeField(auto_now_add=True)
    parent_comment = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.PROTECT,  # 삭제를 막고 싶을 때 사용
        related_name='replies',
        verbose_name='답글 대상 댓글',
    )

    class Meta:
        db_table = 'comment'
        verbose_name = 'AI 대한 댓글창',
        ordering = ['-created_at']







# 기존 llm 이미지 테이블
class LlmBackgroundImage(models.Model):
    llm = models.ForeignKey('customer_ai.LLM', on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    default_img = models.ImageField(upload_to='uploads/default_img/', null=True, blank=True)
    class Meta:
        db_table = 'llm_background_image'
        verbose_name = 'llm 배경사진'

distribute/views.py
from django.shortcuts import render, redirect, get_object_or_404
from mypage.models import  Genre
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
import base64
from makeVoice.models import VoiceList, VoiceLike
from customer_ai.models import LLM, LlmLike
from register.models import Follow
from django.utils.translation import get_language
from home.models import Users
from django.utils.translation import gettext_lazy as _

@csrf_exempt
@login_required
def distribute(request, llm_id):
    llm = get_object_or_404(LLM, id=llm_id, user=request.user)
    genre_list = Genre.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        distribute_text = request.POST.get('distribute')
        selected_genres = request.POST.getlist('genre')
        first_sentence = request.POST.get("first_sentence")

        from django.contrib import messages

        if not distribute_text or not title:
            messages.error(request, _("해당 AI 설명을 해주세요"))
            return redirect("distribute:distribute", llm_id=llm.id)
        elif len(title) > 50:
            messages.error(request, _("AI 제목은 50자 이내입니다."))
            return redirect("distribute:distribute", llm_id=llm.id)
        elif len(genre_list) < 5:
            messages.error(request, _("장르는 5개 까지 선택가능합니다."))
            return redirect("distribute:distribute", llm_id=llm.id)

        llm.title = title
        llm.description = distribute_text
        llm.first_sentence = first_sentence
        llm.is_public = True

        # 장르 ManyToMany 필드 업데이트
        llm.genres.set(selected_genres)



        llm.save()

        return redirect("home:main")

    else:
        # GET 요청 시 기존 선택된 장르 id 문자열 리스트로
        selected_genres = list(map(str, llm.genres.values_list('id', flat=True)))

        llm_list = LLM.objects.filter(user=request.user)

    context = {
        "llm": llm,
        "genre_list": genre_list,
        "selected_genres": selected_genres,
        "llm_list": llm_list
    }
    return render(request, "distribute/distribute.html", context)



@login_required
def unpublish_llm(request, llm_id):
    llm = get_object_or_404(LLM, id=llm_id, user=request.user)
    llm.is_public = False
    llm.save()
    return redirect('mypage:my_ai_models', llm.id)



#ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
# 앱 전용

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.utils.translation import gettext as _

@login_required(login_url='/register/login_app')
def distribute_app(request, llm_id):
    llm = get_object_or_404(LLM, id=llm_id, user=request.user)
    genre_list = Genre.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        distribute_text = request.POST.get('distribute')
        selected_genres = request.POST.getlist('genre')

        from django.contrib import messages

        if not distribute_text or not title:
            messages.error(request, _("AI 설명을 입력해주세요."))
            return redirect('distribute:distribute_app', llm_id=llm.id)
        elif len(title) > 50:
            messages.error(request, _("AI 제목은 50자 이내입니다."))
            return redirect('distribute:distribute_app', llm_id=llm.id)
        elif len(selected_genres) > 5:
            messages.error(request, _("장르는 5개까지 선택 가능합니다."))
            return redirect('distribute:distribute_app', llm_id=llm.id)

        llm.title = title
        llm.description = distribute_text
        llm.is_public = True
        llm.genres.set(selected_genres)
        llm.save()

        return redirect('home:main_app')

    selected_genres = list(map(str, llm.genres.values_list('id', flat=True)))
    llm_list = LLM.objects.filter(user=request.user)

    context = {
        "llm": llm,
        "genre_list": genre_list,
        "selected_genres": selected_genres,
        "llm_list": llm_list,
    }
    return render(request, "distribute/app/distribute_app.html", context)

    



@login_required(login_url='/register/login_app')
def unpublish_llm_app(request, llm_id):
    llm = get_object_or_404(LLM, id=llm_id, user=request.user)
    llm.is_public = False
    llm.save()

    return redirect('mypage:my_ai_models_app', llm.id)


distribute/templates/distribute/distribute.html
{% load static %} 
{% load i18n %}
<!DOCTYPE html>
<html lang="ko">
<head>
<!-- Favicon 설정 -->
<link rel="icon" href="/static/img/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% trans '마이페이지' %} - GALATEA</title>

    <link rel="stylesheet" href="{% static 'css/distribute/distribute.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}" />
        <!-- Open Graph (SNS 공유용) -->
    <meta property="og:title" content="GALATEA AI - 음성 대화형 챗봇" />
    <meta property="og:description" content="자연스러운 음성 대화형 AI 챗봇. 고객과 사람처럼 대화하며 상담과 안내를 제공합니다." />
    <meta property="og:image" content="https://galatea.website/static/img/intro2.png">
    <meta property="og:url" content="https://galatea.website" />
    <meta property="og:type" content="website" />

    <!-- Meta Description (검색 결과용) -->
    <meta name="description" content="문자만 입력하는 챗봇은 이제 그만! GALATEA AI는 음성 기반 대화형 AI로, 실제 사람처럼 대화 경험을 제공합니다. GALATEA AI는 단순한 챗봇이 아닙니다. 음성으로 사람처럼 대화하며, 자연스러운 상담·안내를 제공합니다. 지금 무료 체험으로 직접 경험해보세요. ">

    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "GALATEA AI",
  "url": "https://www.galatea.website",
  "logo": "https://www.galatea.website/static/img/logo.png"
}
</script>

</head>

<body>
    <header>
        {% if not user.is_authenticated %}
            {% include "common/notLoginHeader.html" %}
        {% else %}
            {% include "common/loginHeader.html" %}
        {% endif %}
    </header>
<!-- 배경 원형 효과 -->
<div class="circle-bg circle-1"></div>
<div class="circle-bg circle-2"></div>
<div class="circle-bg circle-3"></div>
<div class="circle-bg circle-4"></div>
<div class="circle-bg circle-5"></div>

<!-- 햄버거 메뉴 버튼 -->
<button class="menu-toggle" onclick="toggleSidebar()">
    <span></span><span></span><span></span>
</button>

<!-- 사이드바 오버레이 (모바일용) -->
<div class="sidebar-overlay" onclick="closeSidebar()"></div>

{% include "common/sidebar.html" %}

<div class="main-content">
    <div class="ai-config-container">

        <!-- **단일 LLM 수정/공유 폼** -->
        <form method="POST" action="{% url 'distribute:distribute' llm.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- AI 이미지 섹션 -->
            <div class="form-group">
                <label>{% trans 'AI 이미지' %}</label>
                <div class="sidebar-profile">
                    {% if llm.llm_image %}
                        <img src="{{ llm.llm_image.url }}" alt="AI 이미지" style="width: 100%; height: 100%; object-fit: cover; border-radius: 15px;" />
                    {% else %}
                        <p style="color: white;">{% trans '생성된 이미지가 없습니다.' %}</p>
                    {% endif %}
                </div>
            </div>

            <!-- 제목 섹션 -->
            <div class="prompt-section">
                <label>{% trans '제목' %}</label>
                <input name="title" class="prompt-textarea" id="titleDisplay" style="height: 50px; margin-bottom: 10px;" value="{{ llm.title }}" placeholder="제목은 50자 이내입니다.">
            </div>

            <div class="distribute-grid">

                <!-- 프롬프트 섹션 -->
                <div class="prompt-section">
                    <label style="margin-bottom: 20px;">{% trans '프롬프트' %}</label>
                    <textarea class="prompt-textarea" id="promptDisplay" readonly>{{ llm.prompt }}</textarea>
                </div>

                <!-- 설명 섹션 -->
                <div class="description-section">
                    <label style="color: black;">{% trans 'AI 모델에 대한 간단한 설명을 작성해주세요' %}</label>
                    <textarea name="distribute" id="distributeDisplay" class="description-textarea" placeholder="{% trans '이 AI는 어떤 특징을 가지고 있나요? 예: 친근하고 유머러스한 대화 상대, 전문적인 조언을 제공하는 컨설턴트 등...' %}">{{ llm.description }}</textarea>
                </div>

                <div class="description-section">
                    <label style="color: black;">{% trans '모델의 첫 마디를 적어주세요' %}</label>
                    <textarea name="first_sentence" id="distributeDisplay" class="description-textarea" placeholder="{% trans '해당 AI 의 첫 마디를 적어주세요.' %}">{{ llm.first_sentence }}</textarea>
                </div>
            </div>

            <!-- 장르 태그 선택 -->
             
            <p>{% trans '장르는 최대 5개까지 선택 가능합니다.' %}</p>
            <div class="genre-tags-container">
                {% for genre in genre_list %}
                    <div class="genre-tag">
                        <input 
                            type="checkbox" 
                            name="genre" 
                            value="{{ genre.id }}" 
                            id="genre_{{ genre.id }}"
                            {% if genre.id|stringformat:"s" in selected_genres %}checked{% endif %}
                        />
                        <label for="genre_{{ genre.id }}" class="genre-tag-label" style="background-color: {{ genre.color }};">
                            <span class="genre-tag-text">{{ genre.name }}</span>
                            <span class="genre-tag-check">✓</span>
                        </label>
                    </div>
                {% endfor %}
            </div>

            <!-- 액션 버튼 -->
            <div style="display: flex; gap: 10px; margin-top: 30px; justify-content: center;">
                {% if llm.is_public %}
                    <button type="submit" class="action-button share-button" onclick="return confirm('{% trans '해당 AI를 정말 공유하시겠습니까?' %}')">
                        {% trans '수정한 내용 공유하기' %}
                    </button>
                {% else %}
                    <button type="submit" class="action-button share-button" onclick="return confirm('{% trans '해당 AI를 정말 공유하시겠습니까?' %}')">
                        {% trans '다른 사람들과 공유하기' %}
                    </button>
                {% endif %}

                <a href="{% url 'mypage:my_ai_models' llm.id %}" class="action-button">{% trans '돌아가기' %}</a>
                {% if llm.is_public %}
                    <a href="{% url 'distribute:unpublic' llm.id %}" class="action-button" onclick="return confirm('{% trans '공유를 취소하시겠습니까?' %}')">{% trans '공유취소하기' %}</a>
                {% endif %}
            </div>

        </form>

    </div>
</div>
<script src="{% static 'js/sidebar.js' %}"></script>

<script src="{% static 'js/distribute/distribute.js' %}">
</script>
{% if messages %}
  <script>
    {% for message in messages %}
      alert("{{ message|escapejs }}");
    {% endfor %}
  </script>
{% endif %}

</body>
</html>