customer_ai/urls.py
from django.urls import path, include
from customer_ai import views
from django.contrib.sitemaps.views import sitemap
from customer_ai.sitemaps import LLMSitemapAllModes
from rest_framework import routers
from customer_ai.views import VoiceListViewSet, LLMViewSet  # ViewSet 불러오기

# Sitemap
sitemaps = {
    'customer_ai': LLMSitemapAllModes(),
}

# REST API Router 생성
router = routers.DefaultRouter()
router.register(r'voice_list', VoiceListViewSet)
router.register(r'llm', LLMViewSet)

# URL Patterns
urlpatterns = [
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),

    path('upload_audio/', views.upload_audio, name='upload_audio'),
    path('generate_response/', views.generate_response, name='generate_response'),
    path('check_audio_status/', views.check_audio_status, name='check_audio_status'),

    path('chat/<int:llm_id>/', views.chat_view, name='chat_view'),
    path('vision/<int:llm_id>/', views.vision_view, name='vision_view'),
    path('novel/<int:llm_id>/', views.novel_view, name='novel_view'),

    path('make_ai/', views.make_ai, name='make_ai'),
    path('image-file/', views.is_allowed_image_file, name='image-file'),
    path('vision_process/', views.vision_process, name='vision_process'),
    path("ai_name/", views.input_ai_name, name="input_ai_name"),
    path('upload_image/', views.upload_image, name='upload_image'),

    # REST API 경로
    path('api/', include(router.urls)),


    # 앱 전용
    path("ai_name_app/", views.ai_name_app, name="ai_name_app"),
    path("make_ai_app/", views.make_ai_app, name="make_ai_app"),
    path("custom_app/<int:llm_id>/", views.custom_app, name="custom_app"),
    path("vision_app/<int:llm_id>/", views.vision_app, name="vision_app"),
    path("novel_app/<int:llm_id>/", views.novel_app, name="novel_app"),

]

distribute/urls.py
from django.urls import path
from distribute import views

app_name = 'distribute'

urlpatterns =[
    path('<int:llm_id>/', views.distribute, name='distribute'),
    path('<int:llm_id>/unpublic/', views.unpublish_llm, name= 'unpublic'),



    path('distribute_app/<int:llm_id>/', views.distribute_app, name= 'distribute_app'),

    path('<int:llm_id>/unpublish_llm_app/', views.unpublish_llm_app, name= 'unpublish_llm_app'),


]

galatea/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from home import views as home_views
from django.views.i18n import set_language
from django.utils.translation import get_language
from django.shortcuts import redirect
from celebrity import views as celebrity_views
from customer_ai import views as customer_ai_views
from makeImage import views as make_image_view
from register import views as login_view
from home import views as main_view
from makeVoice import views as make_voice_view
from helpdesk import views as helpdesk_view
from payment import views as payment_view
from django.contrib.sitemaps.views import sitemap
from home.sitemaps import StaticViewSitemap
from django.views.generic import TemplateView




def root_redirect(request):
    lang = get_language()
    return redirect(f'/{lang}/')

sitemaps = {
    "static": StaticViewSitemap,
}
urlpatterns = [
    path('', root_redirect),  # 루트 접속 시 언어별 URL로 리다이렉트
    path('admin/', admin.site.urls),
    path('i18n/setlang/', set_language, name='set_language'),
    path('accounts/', include('allauth.urls')), 

    path('celebrity/celebrity_audio/', celebrity_views.celebrity_audio, name='celebrity_audio'),
    path('celebrity/<int:celebrity_id>/response/', celebrity_views.celebrity_response, name='celebrity_response'),
    path('upload_audio/', customer_ai_views.upload_audio, name='upload_audio'),
    path('generate_response/', customer_ai_views.generate_response, name='generate_response'),
    path('vision_process/', customer_ai_views.vision_process, name='vision_process'),
    path('novel_process/', customer_ai_views.novel_process, name = "novel_process"),

    path("generate_image/", make_image_view.generate_image, name="generate_image"),
    path('proxy_image/', make_image_view.proxy_image, name='proxy_image'),  # 이미지 프록시용
    path('<int:llm_id>/introduce', main_view.distribute_llm, name='distribute_llm'),
    path("auto_generate_prompt", make_voice_view.auto_generate_prompt, name="auto_generate_prompt") ,           
    path("auto_prompt/", customer_ai_views.auto_prompt, name="auto_prompt"),
    path("payment/complete/", payment_view.payment_complete, name="payment_complete"),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path("robots.txt", TemplateView.as_view(
        template_name="robots.txt",
        content_type="text/plain"
    )),



]



urlpatterns += i18n_patterns(
    
    path('', include('home.urls', namespace='home')),  # home.urls 안에 main/ 포함
    path('celebrity/', include(('celebrity.urls', 'celebrity'), namespace='celebrity')),
    path('customer_ai/', include(('customer_ai.urls', 'customer_ai'), namespace='customer_ai')),
    path('image/', include(('makeImage.urls', 'makeImage'), namespace='makeImage')),
    # path('make_voice/', include(('makeVoice.urls', 'makeVoice'), namespace='makeVoice')),
    path('register/', include(('register.urls', 'register'), namespace='register')),
    path('logout/', home_views.user_logout, name='logout'),
    path('mypage/', include(("mypage.urls","mypage"), namespace="mypage")),
    # path('cloning/', include(('cloning.urls', 'cloning'), namespace='cloning')),
    path('payment/', include(('payment.urls', 'payment'), namespace='payment')),
    path("distribute/", include(("distribute.urls", 'distribute'), namespace="distribute")),
    path('intro/<int:llm_id>/', main_view.llm_detail_partial, name='llm_detail_partial'),
    path('helpdesk/', include(("helpdesk.urls", 'helpdesk'), namespace='helpdesk')),
    path('invest/', include(("invest.urls", 'invest'), namespace='invest')),



    path('api/', include(('customer_ai.urls', 'customer_ai'), namespace='customer_ai_api')),


)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
from home import views as home_views

handler400 = 'home.views.bad_request'
handler403 = 'home.views.permission_denied'
handler404 = 'home.views.page_not_found'
handler500 = 'home.views.server_error'

home/urls.py
from django.urls import path
from home import views
from django.views.i18n import set_language

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),  
    path('main/', views.main, name='main'),
    path('logout/', views.user_logout, name='logout'),
    path('i18n/setlang/', set_language, name='set_language'),
    path('follow/', views.follow_toggle, name = "toggle_follow"),
    path('like/', views.like_toggle, name = 'like_toggle'),
    path('llm/<int:llm_id>/', views.llm_intro, name='llm_intro'),
    path('genres/', views.gerne_all, name= 'genre_all'),
    path('search/', views.search_llm, name = 'search_llm'),
    path('genres/<int:genres_id>', views.genre_detail, name='genres_detail'),
    path('llm_sections/', views.llm_section, name='llm_section'),
    path('comment_create/<int:llm_id>', views.comment_create, name="comment_create"),

    path("voice_all/", views.voice_all, name="voice_all"),
    path("save_voice/", views.save_voice, name="save_voice"),
    path("user_intro/<int:user_id>/", views.user_intro, name="user_intro"),
    path("soon/", views.soon, name="soon"),
    path('invite/', views.invite, name='invite'),


    # path('like/<int:llm_id>/', views.like_toggle, name = "like_toggle"),


    # 앱 전용
    path("app/", views.home_app_view, name="home_app"),
    path("main_app/", views.main_app, name="main_app"),
    path("llm_intro_app/<int:llm_id>/", views.llm_intro_app, name="llm_intro_app"),
    path("llm_section_app/", views.llm_section_app, name="llm_section_app"),
    path("gerne_all_app/", views.gerne_all_app, name="gerne_all_app"),
    path("search_llm_app/", views.search_llm_app, name="search_llm_app"),
    path("genres_detail_app/<int:genres_id>/", views.genres_detail_app, name="genres_detail_app"),
    path("invite_app/", views.invite_app, name="invite_app"),
    path('logout_app/', views.logout_app, name='logout_app'),
    path('voice_all_app/', views.voice_all_app, name='voice_all_app'),
    path('search_result_app/', views.search_result_app, name='search_result_app'),
    path('user_intro_app/<int:user_id>/', views.user_intro_app, name='user_intro_app'),

]


mypage/urls.py
from django.urls import path
from mypage import views

app_name = 'mypage'

urlpatterns = [
    path('', views.mypage_view, name='mypage'),
    path('update/', views.mypage_update, name='mypage_update'),
    path('<int:user_id>/', views.mypage_update, name='mypage_update'),
    path('my_voice/', views.my_voice, name='my_voice'),
    path('my_ai_models/<int:llm_id>/', views.my_ai_models, name='my_ai_models'),
    path('my_ai_conversation/<int:llm_id>/', views.my_ai_conversation, name="my_ai_conversation"),
    path('token/', views.personal_token, name = 'token'),
    path('upload-profile-image/', views.upload_profile_image, name='upload_profile_image'),
    path('my_ai_models/update/<int:llm_id>', views.my_ai_models_update, name='my_ai_models_update'),
    path('my_ai_models/delete/<int:llm_id>', views.my_ai_models_delete, name='my_ai_models_delete'),
    # path('<int:voice_id>/toggle_public/', views.toggle_voice_public, name='toggle_voice_public'),
    path("my_custom/", views.my_custom, name= "my_custom"),
    path("my_request/", views.my_request, name= "my_request"),
    path("my_coupon/", views.my_coupon, name= "my_coupon"),
    path("myvoice/delete/<int:voice_id>/", views.my_voice_delete, name="my_voice_delete"),
    path('personal_profile/', views.personal_profile, name="personal_profile"),
    path('llm_like/', views.llm_like, name="llm_like"),
    path('follow_list/', views.follow_list, name="follow_list"),
    path("unpublish_llm/<int:llm_id>/", views.unpublish_llm, name="unpublish_llm"),
    path('prompt_share/<int:prompt_id>/delete/', views.prompt_share_delete, name='prompt_share_delete'),
    path('prompt_share/<int:prompt_id>/update/', views.prompt_share_update, name='prompt_share_update'),
    path('intro/<int:llm_id>/', views.llm_intro, name='llm_intro'),
    path('token_less/', views.token_less, name='token_less'),
    

    path("mypage_app/", views.mypage_app, name="mypage_app"),
    path('sidebar_app/', views.sidebar_app, name='sidebar_app'),
    path('mypage_update_app/', views.mypage_update_app, name='mypage_update_app'),
    path('my_ai_models_app/<int:llm_id>/', views.my_ai_models_app, name='my_ai_models_app'),
    path('my_ai_conversation_app/<int:llm_id>', views.my_ai_conversation_app, name='my_ai_conversation_app'),
    path('my_voice_app/', views.my_voice_app, name='my_voice_app'),
    path('my_voice_delete_app/', views.my_voice_delete_app, name='my_voice_delete_app'),
    path('my_ai_models_update_app/<int:llm_id>/', views.my_ai_models_update_app, name='my_ai_models_update_app'),
    path('follow_list_app/', views.follow_list_app, name='follow_list_app'),
    path('my_coupon_app/', views.my_coupon_app, name='my_coupon_app'),
    path('token_less_app/', views.token_less_app, name='token_less_app'),
    path('personal_profile_app/', views.personal_profile_app, name='personal_profile_app'),
    path('my_request_app/', views.my_request_app, name='my_request_app'),
    path('llm_like_app/', views.llm_like_app, name='llm_like_app'),
    path('token_app/', views.token_app, name='token_app'),
    path('unpublish_llm_app/<int:llm_id>/', views.unpublish_llm_app, name='unpublish_llm_app'),
    path('my_ai_models/delete_app/<int:llm_id>', views.my_ai_models_delete_app, name='my_ai_models_delete_app'),


]

mypage/models.py
from home.models import Users
from django.db import models
from customer_ai.models import LLM

# 장르 테이블
class Genre(models.Model):
    name = models.CharField(max_length=100, unique=True)
    genre_image = models.ImageField(upload_to='uploads/genre_images/', null=True, blank=True)
    color = models.CharField(max_length=10, default='#FFF', verbose_name='태그 넣을떄 색깔')

    class Meta:
        db_table = 'genres'
        verbose_name = '장르'

    def __str__(self):
        return self.name 
    




mypage/templates/mypage/my_ai_models.html
{% load static %} 
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" style="background-color: #3b0d69;">
<head>
<!-- Favicon 설정 -->
<link rel="icon" href="/static/img/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% trans '마이페이지' %} - GALATEA</title>

    <link rel="stylesheet" href="{% static 'css/mypage/my_ai_models.css' %}?v={{ STATIC_VERSION }}">
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
        <!-- Open Graph (SNS 공유용) -->
    <meta property="og:title" content="GALATEA AI - 음성 대화형 챗봇" />
    <meta property="og:description" content="자연스러운 음성 대화형 AI 챗봇. 고객과 사람처럼 대화하며 상담과 안내를 제공합니다." />
    <meta property="og:image" content="https://galatea.website/static/img/intro2.png">
    <meta property="og:url" content="https://galatea.website" />
    <meta property="og:type" content="website" />

    <!-- Meta Description (검색 결과용) -->
    <meta name="description" content="문자만 입력하는 챗봇은 이제 그만! GALATEA AI는 음성 기반 대화형 AI로, 실제 사람처럼 대화 경험을 제공합니다. GALATEA AI는 단순한 챗봇이 아닙니다. 음성으로 사람처럼 대화하며, 자연스러운 상담·안내를 제공합니다. 지금 무료 체험으로 직접 경험해보세요. ">

    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "GALATEA AI",
  "url": "https://www.galatea.website",
  "logo": "https://www.galatea.website/static/img/logo.png"
}
</script>

</head>
<body>
  
<header>
    {% if not user.is_authenticated %}
        {% include "common/notLoginHeader.html" %}
    {% else %}
        {% include "common/loginHeader.html" %}
    {% endif %}
</header>


    <!-- 햄버거 메뉴 버튼 -->
    <button class="menu-toggle" onclick="toggleSidebar()">
        <span></span>
        <span></span>
        <span></span>
    </button>
    <div class="sidebar-overlay" onclick="closeSidebar()"></div>

    {% include "common/sidebar.html" %}

    <div class="main-content">
        <div class="ai-config-container">
            <!-- 좌측: 이미지, 이름(select), 프롬프트 -->
            <div class="left-section">
                <div class="sidebar-profile">
                    <img id="llmImage" 
                         src="{% if llm_list|length > 0 and llm_list.0.llm_image %}{{ llm_list.0.llm_image.url }}{% endif %}" 
                         alt="{% trans 'AI 이미지' %}"/>
                    <p id="noImageText" style="display: none; color: white;">{% trans '생성된 이미지가 없습니다.' %}</p>
                </div>
                <select id="llmSelect" name="llm_id" onchange="updatePromptAndVoice()">
                    {% for llm in llm_list %}
                    <option
                        value="{{ llm.id }}"
                        data-prompt="{{ llm.prompt|escape }}"
                        data-voice-id="{{ llm.voice.voice_id }}"
                        data-language="{{ llm.language }}"
                        data-stability="{{ llm.stability }}"
                        data-speed="{{ llm.speed }}"
                        data-style="{{ llm.style }}"
                        data-temperature="{{ llm.temperature }}"
                        data-model="{{ llm.model }}"
                        {% if llm.llm_image %}data-llm-image="{{ llm.llm_image.url }}"{% endif %}
                    >
                        {{ llm.name }}
                    </option>
                    {% endfor %}
                </select>
                <div class="prompt-section">
                    <label>{% trans '프롬프트' %}</label>
                    <textarea class="prompt-textarea" id="promptDisplay" readonly></textarea>
                </div>
            </div>

            <!-- 우측: 슬라이더, 언어, voice -->
            <div class="right-sections">
                <div class="language-group">
                    <label>{% trans '언어' %}</label>
                    <div class="language-description">{% trans '언어를 선택해주세요' %}</div>
                    <div class="language-selector" id="languageDisplay">US-en</div>
                </div>
                <div class="slider-container">
                    <div class="slider-label">{% trans '안정감' %}</div>
                    <input class="text" id="stabilitySlider" />
                    <span id="stabilityValue">0.5</span>
                </div>
                <div class="slider-container">
                    <div class="slider-label">{% trans '음성 속도' %}</div>
                    <input class="text" id="speedSlider" />
                    <span id="speedValue">0.5</span>
                </div>
                <div class="slider-container">
                    <div class="slider-label">{% trans '목소리 스타일' %}</div>
                    <input class="text" id="styleSlider" />
                    <span id="styleValue">0.5</span>
                </div>
                <div class="slider-container">
                    <div class="slider-label">{% trans '창의성' %}</div>
                    <input class="text" id="temperatureSlider" />
                    <span id="temperatureValue">0.5</span>
                </div>
                <div class="voice-section">
                    <label>Voice id</label>
                    <input type="text" class="voice-id-input" id="voiceIdDisplay" readonly />
                </div>
            </div>

            <!-- 하단 버튼 -->
            <div class="bottom-section">
                <a href="{% url 'customer_ai:chat_view' llm.id %}" class="action-button">{% trans '대화하기' %}</a>
                <a href="{% url 'mypage:my_ai_models_update' llm.id %}" class="action-button">{% trans '수정하기' %}</a>
                <a href="{% url 'mypage:my_ai_models_delete' llm.id %}" class="action-button delete-button" onclick="return confirm('{% trans "해당 AI를 삭제하시겠습니까?" %}')">{% trans '삭제하기' %}</a>
                {% if llm.is_public %}
                    <a href="{% url 'distribute:distribute' llm.id %}" class="action-button">{% trans '공유한 AI 수정하기' %}</a>
                {% else %}
                    <a href="{% url 'distribute:distribute' llm.id %}" class="action-button">{% trans '공유하기' %}</a>
                {% endif %}
            </div>

            <!-- Hidden inputs -->
            <input type="hidden" id="promptInput" readonly />
            <input type="hidden" id="voiceIdInput" readonly />
            <input type="hidden" id="languageInput" readonly />
            <input type="hidden" id="stabilityInput" readonly />
            <input type="hidden" id="speedInput" readonly />
            <input type="hidden" id="styleInput" readonly />
            <input type="hidden" id="temperatureInput" readonly />
            <input type="hidden" id="modelInput" readonly />
        </div>
    </div>

    <script src="{% static 'js/sidebar.js' %}"></script>
    <script>
        // 초기 UI 세팅
function initializeUIWithCurrentLlm() {
    const initialLlm = {
        id: "{{ llm.id|default:''|escapejs }}",
        prompt: "{{ llm.prompt|default:''|escapejs }}",
        voiceId: "{% if llm.voice %}{{ llm.voice.voice_id|default:''|escapejs }}{% endif %}",
        language: "{{ llm.language|default:''|escapejs }}",
        stability: "{{ llm.stability|default:0.5|escapejs }}",
        speed: "{{ llm.speed|default:0.5|escapejs }}",
        style: "{{ llm.style|default:0.5|escapejs }}",
        temperature: "{{ llm.temperature|default:0.5|escapejs }}",
        model: "{{ llm.model|default:''|escapejs }}",
        llmImage: "{% if llm.llm_image %}{{ llm.llm_image.url }}{% endif %}"
    };

    // 이미지 처리
    const llmImageElem = document.getElementById("llmImage");
    const noImageText = document.getElementById("noImageText");
    if (initialLlm.llmImage) {
        llmImageElem.src = initialLlm.llmImage;
        llmImageElem.style.display = "block";
        noImageText.style.display = "none";
    } else {
        llmImageElem.style.display = "none";
        noImageText.style.display = "block";
    }

    // 텍스트/Voice/Language/Model 설정
    document.getElementById("promptInput").value = initialLlm.prompt;
    document.getElementById("promptDisplay").value = initialLlm.prompt;
    document.getElementById("voiceIdInput").value = initialLlm.voiceId;
    document.getElementById("voiceIdDisplay").value = initialLlm.voiceId;
    document.getElementById("languageInput").value = initialLlm.language;
    document.getElementById("languageDisplay").textContent = initialLlm.language;
    document.getElementById("modelInput").value = initialLlm.model;
    if(document.getElementById("modelDisplay")){
        document.getElementById("modelDisplay").textContent = initialLlm.model;
    }

    // 슬라이더 초기화
    const sliders = ["stability", "speed", "style", "temperature"];
    sliders.forEach(slider => {
        const sliderElem = document.getElementById(`${slider}Slider`);
        const valueElem = document.getElementById(`${slider}Value`);
        const inputElem = document.getElementById(`${slider}Input`);
        if(sliderElem && valueElem && inputElem){
            sliderElem.value = initialLlm[slider];
            valueElem.textContent = initialLlm[slider];
            inputElem.value = initialLlm[slider];
        }
    });

    // select 초기값 설정
    const llmSelect = document.getElementById("llmSelect");
    if (llmSelect && initialLlm.id) {
        for (let i = 0; i < llmSelect.options.length; i++) {
            if (llmSelect.options[i].value === initialLlm.id) {
                llmSelect.selectedIndex = i;
                break;
            }
        }
    }
}

// 선택된 LLM 업데이트
function updatePromptAndVoice() {
    const llmSelect = document.getElementById("llmSelect");
    const selectedOption = llmSelect.options[llmSelect.selectedIndex];

    // URL 업데이트
    const selectedLlmId = selectedOption.value;
    const currentPath = window.location.pathname;
    const newUrl = currentPath.replace(/\/my_ai_models\/(\d+)\/?$/, `/my_ai_models/${selectedLlmId}/`);
    if (window.location.pathname !== newUrl) window.location.href = newUrl;

    // 프롬프트/Voice 업데이트
    document.getElementById("promptDisplay").value = selectedOption.dataset.prompt || "";
    document.getElementById("voiceIdDisplay").value = selectedOption.dataset.voiceId || "";
    document.getElementById("voiceIdInput").value = selectedOption.dataset.voiceId || "";
    document.getElementById("languageDisplay").textContent = selectedOption.dataset.language || "";
    document.getElementById("languageInput").value = selectedOption.dataset.language || "";

    // 슬라이더 업데이트
    const sliders = ["stability", "speed", "style", "temperature"];
    sliders.forEach(slider => {
        const value = selectedOption.dataset[slider] || 0.5;
        const sliderElem = document.getElementById(`${slider}Slider`);
        const valueElem = document.getElementById(`${slider}Value`);
        const inputElem = document.getElementById(`${slider}Input`);
        if(sliderElem && valueElem && inputElem){
            sliderElem.value = value;
            valueElem.textContent = value;
            inputElem.value = value;
        }
    });

    // 이미지 업데이트
    const llmImageElem = document.getElementById("llmImage");
    const noImageText = document.getElementById("noImageText");
    if (selectedOption.dataset.llmImage) {
        llmImageElem.src = selectedOption.dataset.llmImage;
        llmImageElem.style.display = "block";
        noImageText.style.display = "none";
    } else {
        llmImageElem.style.display = "none";
        noImageText.style.display = "block";
    }
}

// 슬라이더 이벤트 리스너 설정
function setupSliderListeners() {
    const sliders = ["stability", "speed", "style", "temperature"];
    sliders.forEach(slider => {
        const sliderElem = document.getElementById(`${slider}Slider`);
        const valueElem = document.getElementById(`${slider}Value`);
        const inputElem = document.getElementById(`${slider}Input`);
        if(sliderElem && valueElem && inputElem){
            sliderElem.oninput = () => {
                valueElem.textContent = sliderElem.value;
                inputElem.value = sliderElem.value;
            };
        }
    });
}

// 초기화
window.onload = function () {
    initializeUIWithCurrentLlm();
    setupSliderListeners();
};


    </script>

</body>
</html>

mypage/templates/mypage/my_request.html
{% load static %}
{% load i18n %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}" style="background-color: #3b0d69;">
<head>
<!-- Favicon 설정 -->
<link rel="icon" href="/static/img/favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="/static/img/favicon.ico" type="image/x-icon">

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{% trans "마이페이지 - GALATEA" %}</title>
    <link rel="stylesheet" href="{% static 'css/mypage/my_voice.css' %}" />
    <link rel="stylesheet" href="{% static 'css/sidebar.css' %}">
    <link rel="stylesheet" href="{% static 'css/mypage/my_request.css' %}">
        <!-- Open Graph (SNS 공유용) -->
    <meta property="og:title" content="GALATEA AI - 음성 대화형 챗봇" />
    <meta property="og:description" content="자연스러운 음성 대화형 AI 챗봇. 고객과 사람처럼 대화하며 상담과 안내를 제공합니다." />
    <meta property="og:image" content="https://galatea.website/static/img/intro2.png">
    <meta property="og:url" content="https://galatea.website" />
    <meta property="og:type" content="website" />

    <!-- Meta Description (검색 결과용) -->
    <meta name="description" content="문자만 입력하는 챗봇은 이제 그만! GALATEA AI는 음성 기반 대화형 AI로, 실제 사람처럼 대화 경험을 제공합니다. GALATEA AI는 단순한 챗봇이 아닙니다. 음성으로 사람처럼 대화하며, 자연스러운 상담·안내를 제공합니다. 지금 무료 체험으로 직접 경험해보세요. ">

    <script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "name": "GALATEA AI",
  "url": "https://www.galatea.website",
  "logo": "https://www.galatea.website/static/img/logo.png"
}
</script>

</head>
<body>
  
<header>
    {% if not user.is_authenticated %}
        {% include "common/notLoginHeader.html" %}
    {% else %}
        {% include "common/loginHeader.html" %}
    {% endif %}
</header>
   <!-- 배경 원형 효과 (distribute.css에서 사용) -->
    <div class="circle-bg circle-1"></div>
    <div class="circle-bg circle-2"></div>
    <div class="circle-bg circle-3"></div>
    <div class="circle-bg circle-4"></div>
    <div class="circle-bg circle-5"></div>

    <!-- 햄버거 메뉴 버튼 (모바일용) -->
    <button class="menu-toggle" onclick="toggleSidebar()">
        <span></span>
        <span></span>
        <span></span>
    </button>

    <!-- 사이드바 오버레이 (모바일용) -->
    <div class="sidebar-overlay" onclick="closeSidebar()"></div>

    {% include "common/sidebar.html" %}
    
    <div class="request-container">
        <h1 class="page-title">{% trans "나의 요청글 목록" %}</h1>
        
        {% if request_list %}
            {% for request in request_list %}
                <div class="request-item">
                    <div class="status-indicator {% if not request.response %}pending{% endif %}"></div>
                    
                    <div class="request-title">{{ request.title }}</div>
                    
                    <div class="request-content">{{ request.content }}</div>
                    
                    <div class="request-response">
                        {% if request.response %}
                            {{ request.response }}
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        {% else %}
            <div class="empty-message">
                <p>{% trans "아직 요청글이 없습니다." %}</p>
            </div>
        {% endif %}
    </div>

</body>
</html>